version: '3'
services:
  imageservice:
    build: .
    ports:
      - "60000:60000"
  db:
    image: "postgres:11.1-alpine"
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "60001:5432"
  memcached:
    image: "memcached:1.5.12-alpine"
    ports:
      - "60002:11211"
  redis:
    image: "redis:5.0.3-alpine"
    ports:
      - "60003:6379"
